#!/usr/bin/env bash

# Set to "fuzzel", "rofi", "wofi", "bemenu", or "dmenu" to force a specific launcher. 
# Leave empty to auto-detect!
LAUNCHER_OVERRIDE=""

if [[ "$1" == "query" && "$2" == "default" && -n "$3" ]]; then
    DEFAULT=$(/usr/bin/xdg-mime "$@")
    [[ -n "$DEFAULT" && -n $(find /usr/share/applications ~/.local/share/applications -type f -name "$DEFAULT" 2>/dev/null | head -n 1) ]] && {
        echo "$DEFAULT"
        exit 0
    }

    if [[ "$LAUNCHER_OVERRIDE" == "fuzzel" || ( -z "$LAUNCHER_OVERRIDE" && -x "$(command -v fuzzel)" ) ]]; then
        MENU_CMD=(fuzzel --dmenu --prompt="App for $3: ")
    elif [[ "$LAUNCHER_OVERRIDE" == "rofi" || ( -z "$LAUNCHER_OVERRIDE" && -x "$(command -v rofi)" ) ]]; then
        MENU_CMD=(rofi -dmenu -p "App for $3: ")
    elif [[ "$LAUNCHER_OVERRIDE" == "wofi" || ( -z "$LAUNCHER_OVERRIDE" && -x "$(command -v wofi)" ) ]]; then
        MENU_CMD=(wofi --dmenu --prompt="App for $3: ")
    elif [[ "$LAUNCHER_OVERRIDE" == "bemenu" || ( -z "$LAUNCHER_OVERRIDE" && -x "$(command -v bemenu)" ) ]]; then
        MENU_CMD=(bemenu -p "App for $3: ")
    elif [[ "$LAUNCHER_OVERRIDE" == "tofi" || ( -z "$LAUNCHER_OVERRIDE" && -x "$(command -v tofi)" ) ]]; then
        MENU_CMD=(tofi --prompt-text "App for $3: ")
    elif [[ "$LAUNCHER_OVERRIDE" == "dmenu" || ( -z "$LAUNCHER_OVERRIDE" && -x "$(command -v dmenu)" ) ]]; then
        MENU_CMD=(dmenu -p "App for $3: ")
    else
        notify-send "xdg-mimic" "No application launcher found!"
        exit 1
    fi

    [[ "${MENU_CMD[0]}" =~ ^(fuzzel|rofi)$ ]] && SUPPORTS_ICONS=1

    if CHOSEN=$(find ~/.local/share/applications /usr/share/applications -type f -name "*.desktop" 2>/dev/null | awk -v icons="${SUPPORTS_ICONS:-0}" -F/ '
        BEGIN {
            fmt = icons ? "%s\0icon\x1f%s\n" : "%s\n"
        }
        {
            name = substr($NF, 1, length($NF) - 8)
            if (seen[name]++) next
            icon = ""
            while ((getline line < $0) > 0) {
                if (index(line, "Icon=") == 1) {
                    icon = substr(line, 6)
                    break
                }
            }
            close($0)
            printf fmt, name, icon
        }
    ' | sort | "${MENU_CMD[@]}" 2>/dev/null); then
        /usr/bin/xdg-mime default "${CHOSEN}.desktop" "$3"
        echo "${CHOSEN}.desktop"
    fi
else
    exec /usr/bin/xdg-mime "$@"
fi
